name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4

      - name: 🔢 Adjust version number
        shell: bash
        run: |
          version="${{ github.event.release.tag_name }}"
          version="${version,,}"
          version="${version#v}"
          jq --arg version "$version" '.version=$version' \
            "${{ github.workspace }}/custom_components/cameralux/manifest.json" \
            > "${{ github.workspace }}/custom_components/cameralux/manifest.json.tmp"
          mv "${{ github.workspace }}/custom_components/cameralux/manifest.json.tmp" \
             "${{ github.workspace }}/custom_components/cameralux/manifest.json"

      - name: 📦 Created zipped release package
        run: |
          cd "${{ github.workspace }}/custom_components/cameralux"
          zip cameralux.zip -r ./

      - name: ⬆️ Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "${{ github.workspace }}/custom_components/cameralux/cameralux.zip"
          asset_name: cameralux.zip
          tag: ${{ github.ref }}
          overwrite: true
